public class Car {

    public void switchOn() {
        system.debug('starting the car nowww!');
    }

    //Go to classes (force-app>classes) folder > right click create apex class
    ////remove the extra stuff.

    //How to save this code to ORG?
        //1. save (ctrl + s) (cmd + s)
        //2. Deploy ?
            // right click > Sfdx deploy
    //what happens when we deploy? [we are NOT executing]
    //it will save the code to the org.
}