car vw = new car();
vw.carColor = 'beyaz';
vw.carName = 'hacı murat 😁';
vw.switchOn();



vw.switchOn();
vw.drive();
vw.driveAtMaxSpeed();


car bm = new car();
bm.carColor = 'Black';
system.debug('bm ==> ' + bm);
bm.switchOn();
system.debug('bm color => ' + bm.carColor);

car lm = new car();
lm.carColor = 'red';
//lm.maxSpeed = 200;
lm.switchOn();
//system.debug('lm max speed => ' + lm.maxSpeed);